### ISSUE TITLE
Unable to run swift build command

### ISSUE THREAD

**Issue by kusumarakesh** [tayloraswift/swift-png#66]
When we try to run the Swift Package commands like
1. swift build
2. swift tests

The build is failing with below reason. Any help is highly appreciated. Thanks

<img width="1296" alt="Screenshot 2024-04-12 at 10 11 43 PM" src="https://github.com/tayloraswift/swift-png/assets/103421485/114793c6-2f1a-4af8-8a89-dffff146c42d">

**Comment by tayloraswift** [comment]
what platform are you on?
