### ISSUE TITLE
Not supported for Xcode 17 beta

### ISSUE THREAD

**Issue by kusumarakesh** [tayloraswift/swift-png#70]
Unfortunately the sdk is not compiling for Xcode 17

<img width="1704" alt="Screenshot 2024-07-07 at 12 41 02 PM" src="https://github.com/tayloraswift/swift-png/assets/103421485/18ac7cd1-97f7-4083-8ede-a02f66fb1859">

**Comment by tayloraswift** [comment]
looks like a duplicate of #68

**Comment by kusumarakesh** [comment]
Thanks @tayloraswift
